name: 'GO: Test and Lint'
description: 'Runs go test and golangci-lint'
runs:
  using: "composite"
  steps:
    - name: Test
      run: go test -v ./...
      shell: bash
    - name: Lint
      run: |-
        # golangci-lint recommends binary installation https://golangci-lint.run/usage/install/#ci-installation
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1
        go get -u github.com/bradleyfalzon/revgrep/...
        ./bin/golangci-lint run -E goimports -E bodyclose --deadline 360s |& revgrep origin/main
      shell: bash